# Site settings
title: FlipSkills
description: > # this means to ignore newlines until "email:"
  We work with organizations all over the globe to fuel collaboration, 
  enhance creativity, and develop today’s essential workplace capabilities: 
  Followership, Leadership, innovation & Partnership skills.
email: info@flipskills.com
phone_number: 647-296-6054
address: > # this means to ignore newlines until "url:"
  Liberty Village
  Toronto, ON
  Canada
url: "http://www.flipskills.com/" # the base hostname & protocol for your site
baseurl: ""
twitter: 
facebook: 
linkin: https://www.linkedin.com/company/flipskills-consulting

# Build settings
markdown: kramdown
sass:
  style: compressed